spring.application.name=ms-rutaexpress-envios

# ===== Conexion Oracle Cloud (Autonomous DB con Wallet) =====
spring.datasource.url=${ORACLE_DB_URL}
spring.datasource.username=${ORACLE_ENVIOS_USERNAME}
spring.datasource.password=${ORACLE_ENVIOS_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Ubicacion del wallet
oracle.net.tns_admin=${ORACLE_WALLET_LOCATION}
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=${ORACLE_WALLET_LOCATION}

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false